### ISSUE TITLE
support for attributes values containing an equal sign in them

### ISSUE THREAD

**Issue by smeevil** [slime-lang/slime#10]
example :

meta content="width=device-width, initial-scale=1", name="viewport"

**Comment by doomspork** [comment]
Good catch, thank you @smeevil.

**Comment by Rakoth** [comment]
Hi, I have an easy fix for this one, https://github.com/Rakoth/slim_fast/commit/a015015a2e002f004ffdb72562e50e49c878d090
Did I miss something or I can go on with PR?

**Comment by doomspork** [comment]
Looks good to me @Rakoth :+1:
