### ISSUE TITLE
Support data-attributes with empty values

### ISSUE THREAD

**Issue by lessless** [slime-lang/slime#104]
Hello,

As of now data attributes w/o value or which value is an empty string are not being rendered. 
For example:

`a.toggle.fa.fa-bars href="#" data-toggle=""` is rendered as `<a class="toggle fa fa-bars" href="#"></a>`
and the same goes for `a.toggle.fa.fa-bars href="#" data-toggle` - `<a class="toggle fa fa-bars" href="#"></a>`

I know that might sound like a not a widespread case, but it has a place in Foundation framework, for example, http://foundation.zurb.com/sites/docs/responsive-navigation.html

**Comment by doomspork** [comment]
Thanks for the report @lessless!  Do you want to take a whack at fixing this?  I believe the offending line is here: https://github.com/slime-lang/slime/blob/master/lib/slime/compiler.ex#L25

**Comment by lessless** [comment]
My pleasure!

Upon looking at the tests I figured out that passing boolean `true` as an attribute's value will render just attribute itself `a.toggle.fa.fa-bars href="#" data-toggle=true` -> `<a class="toggle fa fa-bars" href="#" data-toggle=""></a>`, which totally closes the second case. 

As for the empty string -  I wrote following test and it passed all of a sudden

```
tree = [
      %HTMLNode{
        tag: :div,
        attributes: ["data-time": [""]]}
    ]
    expected = ~s(<div data-time=""></div>)
    assert Compiler.compile(tree) == expected
```

Maybe I need to update to latest version - `"slime": {:hex, :slime, "0.13.0", "fb9b1296b5ef3fe6aed09deec2794a146c94f5270b3bcd9f956c01d3660fc196", [:mix], []},`

Just removing the line you mentioned didn't break anything, but I'll better try it off on the local project before submitting a PR :)

**Comment by lessless** [comment]
My cased was  resolved  with `data-time=true` and since I don't have enough time I'll close this. 
Sorry folks.
