### ISSUE TITLE
Ability to output with trailing and leading whitespace

### ISSUE THREAD

**Issue by naps62** [slime-lang/slime#109]
[The slim docs explain](http://www.rubydoc.info/gems/slim/frames#Output__) that you can use `=<` and `=>` to output an evaluated expression with a leading or trailing whitespace.

This doesn't seem to work with this library

**Comment by doomspork** [comment]
Thank you for the report @naps62!  Would you like to take a stab at implementing this?

**Comment by naps62** [comment]
@doomspork I was actually trying that right after I opened the issue, but ended up being a bit more complex that I thought (or I wasn't going at it the right way)

I'll have some time again today, and will try again

**Comment by doomspork** [comment]
This was handled by @kerryb in #120
