### ISSUE TITLE
Support boolean attributes

### ISSUE THREAD

**Issue by smeevil** [slime-lang/slime#11]
input(type="password" required)

should become <input type="password" required>

**Comment by doomspork** [comment]
I was looking at this one last night, thanks for adding it.  I updated the title since I _believe_ this only applies to boolean attributes: https://github.com/slim-template/slim#boolean-attributes

Thanks!

**Comment by doomspork** [comment]
@Rakoth just a heads up I'm working on this one.  I should have a PR by the end of the day (PST), I'd love to get your feedback!
