### ISSUE TITLE
Easier spacing of HTML tags in sentences

### ISSUE THREAD

**Issue by marceldegraaf** [slime-lang/slime#111]
Is there a way to get around using lots of `'` to make sure HTML tags in sentences are spaced correctly?

This code:

```
strong Head's up!
'
' This is
strong a preview
'
' of the
'
strong= @landing_page.name
'
' landing page
```

Renders correctly: `<p><strong>Head's up!</strong> This is <strong>a preview</strong> of the  <strong>Foobar</strong> landing page </p>` (note the spacing before the `<strong>` tags and after the `</strong>` tags)

However, I would like to do this:

```
strong Head's up!
' This is
strong a preview
' of the
strong= @landing_page.name
' landing page
```

But that renders as `<p><strong>Head's up!</strong>This is <strong>a preview</strong>of the <strong>Foobar</strong>landing page </p>` (the next word comes right after the `</strong>` tag, without a space in between)

**Comment by Rakoth** [comment]
Hi! You can use `strong<>` to ensure spaces around tag
https://github.com/slim-template/slim#trailing-and-leading-whitespace--

**Comment by marceldegraaf** [comment]
Oh, nice, I never knew that existed. Thanks!
