### ISSUE TITLE
empty or single space attributes are stripped

### ISSUE THREAD

**Issue by mikelat** [slime-lang/slime#112]
I write something like
`option value="" choice 1`

I expect
`<option value="">choice 1</option>`

I get
`<option>choice 1</option>`

It looks like the attributes are being stripped, so I can't even add a space.

Thanks

**Comment by Rakoth** [comment]
Hi @mikelat ! This is correct, since original slim-lang do the same in this case.
Use `value=true` if you want boolean-attribute like `async` or `checked`.

**Comment by mikelat** [comment]
Alright, if that is what you intend then I'll work around it.

Thanks for the work you fellas put into this!
