### ISSUE TITLE
Allow for unescaped text interpolation

### ISSUE THREAD

**Issue by bfad** [slime-lang/slime#114]
Slim allows for unescaped interpolation by using `#{{expression}}` (http://www.rubydoc.info/gems/slim/frames#Text_interpolation). It would be great for slime to have some way to do this as well.

This is particularly handy when needing to inject JSON data into javascript:

```
javascript:
  var data = #{Poison.encode! my_data}
```

**Comment by doomspork** [comment]
@bfad this would be a great feature to have, would you like to take a shot at adding it?

**Comment by bfad** [comment]
@doomspork I took a brief look, and unfortunately I don't have the time to dig into it further right now. It looked like to me that the places where the code is parsing stuff of `:eex` need to be looked at:

https://github.com/slime-lang/slime/blob/master/lib/slime/parser.ex#L91
https://github.com/slime-lang/slime/blob/master/lib/slime/parser.ex#L138
https://github.com/slime-lang/slime/blob/master/lib/slime/parser.ex#L292

But I'm not sure how to get it to tell EEX not escape the result.

**Comment by almassapargali** [comment]
Currently I'm doing: 

```
eex:
  <script type="text/javascript">
    window.r_AppData = <%= {:safe, app_data_json(@conn)} %>
  </script>

# LayoutView.ex

  def app_data_json(conn) do
    Poison.encode! %{
      MyData: conn.assigns.my_data,
    }
  end
```

You have to pass `{:safe, str}` to tell EEX not to escape.
