### ISSUE TITLE
Compilation errors always points line 1 in templates.

### ISSUE THREAD

**Issue by bfcns** [slime-lang/slime#118]
Any compilation error due to a slim template causes the error output to show as it is on line 1, which is not necessarily true, and makes it hard to debug, as an example below:

```
== Compilation error on file web/views/layout_view.ex ==
** (TokenMissingError) web/templates/layout/_header.html.slim:1: missing terminator: " (for string starting at line 1)
```

**Comment by Rakoth** [comment]
Hi, @phpcitizen sounds like config option would help you.
add to your `config/dev.exs`
```
config :slime, :keep_lines, true
```

Keep in mind a bit different behaviour https://github.com/slime-lang/slime#debugging

**Comment by bfcns** [comment]
Thanks a lot for your prompt solution/reply.

**Comment by doomspork** [comment]
@Rakoth is the 💣 

Glad that worked for you @phpcitizen 👍
