### ISSUE TITLE
support for dashed-classes

### ISSUE THREAD

**Issue by smeevil** [slime-lang/slime#12]
.my-css-class test

should become 

<div class="my-css-class">test</div>

currently : 

<div class="some-thing">-thing test</div>

**Comment by doomspork** [comment]
I'm going to consider this one a bug as I thought this functionality existed, I'll look at this one first.

Thanks @smeevil!

**Comment by doomspork** [comment]
This should be fixed in master @smeevil, I will prepare a patch release shortly.
