### ISSUE TITLE
Multiline list of attributes

### ISSUE THREAD

**Issue by HenriMorlaye** [slime-lang/slime#121]
Hi,
Is there a way to split long attribute lists into several lines ? I tried:
```
input[
  type="text"
  class="form-control"
  name="plop"]
```
without success.

**Comment by johannesE** [comment]
Same here. It gives me

    (Slime.TemplateSyntaxError) Can't find matching delimiter "]" in line " id="asdf""
    (slime) lib/slime/parser.ex:308: Slime.Parser.parse_wrapped_attributes/2
    (slime) lib/slime/parser.ex:216: Slime.Parser.parse_line/2
    (slime) lib/slime/parser.ex:75: Slime.Parser.parse_line/1
    (slime) lib/slime/parser.ex:47: Slime.Parser.parse_lines/2
    (slime) lib/slime/renderer.ex:20: Slime.Renderer.precompile/1
    (phoenix_slime) lib/phoenix_slime/engine.ex:9: PhoenixSlime.Engine.compile/2
    (phoenix) lib/phoenix/template.ex:378: Phoenix.Template.compile/2

**Comment by doomspork** [comment]
Howdy @HenriMorlaye and @johannesE, this is not currently supported.  We could certainly look into it, if either of you'd like to give it a shot PRs are welcomed 👍

**Comment by johannesE** [comment]
I'm still new to elixir, but I'm giving it a try :)
My first Idea was to join these lines in the preprocessor, but if I look at the way you handle the rest of the stuff (e.g. eex lines), I guess you'd want me to add it in the parser.
Btw I love how fast the tests run. No database, dependency or anything. :-)
