### ISSUE TITLE
"%" symbol in attributes does not work

### ISSUE THREAD

**Issue by hubertlepicki** [slime-lang/slime#123]
This is slightly weird bug. I have a use case where i want to set up some data-* attributes. I am doing it this way:

    div#foo data-label="Remaining %"

and this works great. The problem starts when I wrap this string in a function call, for example:

    div#foo data-label=gettext("Remaining %")

or

    div#foo data-label=escape_javascript("Remaining %")

I am getting the following error:

> == Compilation error on file lib/user_interface/views/projects_view.ex ==
> ** (TokenMissingError) lib/user_interface/templates/projects/show.html.slim:1: missing terminator: " (for string starting at line 1)
>     (eex) lib/eex/compiler.ex:36: EEx.Compiler.generate_buffer/4
>     (phoenix) lib/phoenix/template.ex:378: Phoenix.Template.compile/2
>     (phoenix) lib/phoenix/template.ex:186: Phoenix.Template."-MACRO-__before_compile__/2-fun-0-"/3
>     (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
>     (phoenix) expanding macro: Phoenix.Template.__before_compile__/1
>     lib/user_interface/views/projects_view.ex:1: FooApp.UserInterface.ProjectsView (module)
>     (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

The workaround I am using is to wrap the `gettext("Remaining %")` into one more function, put that function in a view and call it in the template such as:

    div#foo data-label=remaining_label()

where in my view:

    def remaining_label do 
      gettext("Remaining %")
    end

**Comment by Rakoth** [comment]
Hi, @hubertlepicki. Thanks for the bug report! 
I would suggest to try my fork https://github.com/Rakoth/slime until #113 is merged.

**Comment by Rakoth** [comment]
closed by #113
