### ISSUE TITLE
Consider removing IE conditionals (/[if IE])

### ISSUE THREAD

**Issue by little-bobby-tables** [slime-lang/slime#127]
Support for conditional comments was removed in IE10, which itself has reached the end of life [more than a year ago](https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support). 

That's not the main reason I'm bringing this up, however. The problem is in the way it's currently implemented in Slime: the content of the conditional is not parsed ([like it should be](https://github.com/slim-template/slim/blob/17dd4a04752c27e20ac0350b438b5de2724bb4de/test/core/test_html_structure.rb#L404)), rather, it is treated as plain text. This defeats the purpose of `<!--[if IE]>`, which is to inject browser-specific _DOM elements_. 

Fixing the behavior will increase the complexity of the parser — why not just remove it? In case it's absolutely necessary, the conditionals can be inserted as ordinary HTML tags anyway:
```
<!--[if IE 9]>
    p Get a better browser
<![endif]-->
```

**Comment by Rakoth** [comment]
+1 to drop support

**Comment by doomspork** [comment]
Let's remove it!

**Comment by Rakoth** [comment]
closed by #128
