### ISSUE TITLE
Releasing a new version

### ISSUE THREAD

**Issue by doomspork** [slime-lang/slime#129]
@Rakoth we need to cut a new release with your changes and @little-bobby-tables's newest additions.  Since there has been a significant shift in the goals of the project (not an exact 1:1 w/ Slim, respecting Elixir along the way) and the implemention how do you feel about cutting `v1.0` and going from there?

**Comment by Rakoth** [comment]
@doomspork with #130 merged we are good to go with 1.0 I think!

**Comment by little-bobby-tables** [comment]
I'm eager to use the new version in my project, so if you need any help, say, with the changelog, I'd be glad to lend a hand.

**Comment by Rakoth** [comment]
Thanks, @little-bobby-tables I am on it

**Comment by doomspork** [comment]
@Rakoth thank you!  You can push to hex, correct?  If you cannot, I can need to add you to hex.

**Comment by Rakoth** [comment]
Done https://hex.pm/packages/slime/1.0.0
