### ISSUE TITLE
New version with windows bug fix

### ISSUE THREAD

**Issue by tmbb** [slime-lang/slime#138]
Should we release a 1.0.1 version to fix the windows bugs? I think it's a matter of time before other windows users are affected by the bug.

**Comment by Rakoth** [comment]
Sure, @tmbb but I also want to include fix for #131 when I have a minute, I will look into it

**Comment by doomspork** [comment]
@Rakoth now that #143 and #144 are merged, do you want to cut a new release?  I'd be happy to do so.

**Comment by Rakoth** [comment]
@doomspork yep, you good to go with new release

**Comment by tmbb** [comment]
It hasn't been release yet, has it?

**Comment by doomspork** [comment]
@tmbb this has been released as 1.1.0 — sorry for the delay.

**Comment by Rakoth** [comment]
Done
