### ISSUE TITLE
Add support for leading/trailing space control to dynamic_content

### ISSUE THREAD

**Issue by paradox460** [slime-lang/slime#142]
In Ruby Slim, I can write the following:

```slim
.foo
  => 'bar'
  =< 'baz'
```

and get the following

```html
<div class="foo">
  bar  baz
</div>
```

This code causes a parsing error in slime.

----

The [Slim docs](http://www.rubydoc.info/gems/slim/frames#Output__) explicitly call out the ability to use `<` and `>` to control leading/trailing spaces with dynamic content:

> For trailing or leading whitespace the modifiers > and < are supported.
> + Output with trailing white space =>. Same as the single equals sign (=), except that it adds a trailing white space.
> + Output with leading white space =<. Same as the single equals sign (=), except that it adds a leading white space.

It also mentions that the above syntax works with double-equals (`==`).

**Comment by Rakoth** [comment]
Hi, @paradox460! Which version of Slime are you using? Just tested your example in master, it works as expected.

**Comment by paradox460** [comment]
Ah, I see that you do support it in master and 1.0, but my project is using phoenix-slime, which doesn't support more than 0.9

**Comment by Rakoth** [comment]
@paradox460 you could override slime version in your project's deps:
```
[
  ...
  {:slime, "~> 1.0", override: true},
]
```
