### ISSUE TITLE
How do I define javascript type in this ? 

### ISSUE THREAD

**Issue by doraeminemon** [slime-lang/slime#148]
I'm having a part of js with type=module. How do I define it in this ? 
Using the normal script tag and it is inconvenient when I'm having about 20 lines of code.

```slim
  script type="module"
  | import autoComplete from 'js/app'
```

**Comment by Rakoth** [comment]
Hi! You could achieve this by defining custom embedded engine:

in file `config.exs`:
```
config :slime, :embedded_engines, %{
  javascript_module: MyApp.SlimeJavascriptModuleEngine
}
```

and engine module may look like this:
```
defmodule MyApp.SlimeJavascriptModuleEngine do
  @behaviour Slime.Parser.EmbeddedEngine

  def render(text, _options) do
    {"script", attributes: [type: "module"], children: text}
  end
end
```

and then use it like so:

```
javascript_module:
  ...
```

https://github.com/slime-lang/slime#embedded-engines

**Comment by doraeminemon** [comment]
Thanks ! This will do.
