### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by navinpeiris** [slime-lang/slime#149]
It'll be awesome if we can get a release with the commit 002e3433afea8a37722d9cf95e9a010bfe90dca2 which addresses issue #147.

Writing Vue.js templates inline is pretty cumbersome without that as you have to depend on master or use some very dodgy workarounds.

Thanks!

**Comment by Rakoth** [comment]
Done https://github.com/slime-lang/slime/releases/tag/v1.2.0
