### ISSUE TITLE
Support Elixir 1.8

### ISSUE THREAD

**Issue by doomspork** [slime-lang/slime#152]
As raised in https://github.com/slime-lang/phoenix_slime/issues/68 we need to assess 1.8 support and incorporate any necessary changes.

**Comment by stevegraham** [comment]
FYI I just ran the following on 1.8 and it worked completely fine. Not sure where my problem lies, I will try to dig in.

```elixir
source = """
doctype html
html
  head
    meta name="keywords" description="Slime"
    title = site_title
    javascript:
      alert('Slime supports embedded javascript!');
  body
    #id.class
      ul
        = Enum.map [1, 2], fn x ->
          li = x
"""

Slime.render(source, site_title: "lol")
```
