### ISSUE TITLE
Evaluating elixir module in custom embedded engine

### ISSUE THREAD

**Issue by edisonywh** [slime-lang/slime#153]
I’m having an issue with embedded engine, trying to define a custom engine called `markdown` (as per the README)

I have a `@markdown` passed down from my Phoenix controller, but it renders `@markdown` literally when I do so:

```
markdown:
    @markdown
```

which makes obvious sense because the whole thing is passed into it, but was wondering if there's any way to evaluate the binding at that point of time and then pass that down?

I'm looking at https://github.com/slime-lang/slime/blob/master/lib/slime/parser/embedded_engine.ex which might be relevant, but can't really figure it out. Any advice?

**Comment by doomspork** [comment]
Howdy @edisonywh! I think there may be a misunderstanding as to how this works. I believe relevant section of the README you're looking for is here: https://github.com/slime-lang/slime#embedded-engines

I'm not entirely sure what you want to happen will though.  For example `@markdown` is not valid markdown and won't work. You'd need Slime to resolve `@markdown` to the markdown you provided and then Slime would have to pass that to the other engine, that's not how it works.

The engines should be used with code that's static, of that type:

```elixir

markdown:
  # This is a header
  __other markdown__ _values_
```

Why not convert the markdown to HTML in your controller?

**Comment by edisonywh** [comment]
Hey thanks for the quick reply!

What I intend to happen is that, I currently have a markdown string passed down from my phoenix controller, and I want to be able to render that in a markdown engine, but it seems like the markdown engine can only render static contents like what you suggested.

e.g:

```
@my_markdown_from_controller = "# This would not work"

markdown:
  @my_markdown_from_controller

#=> This will render `@my_markdown_from_controller` literally, and not  `# This would not work`
```

Does that make sense? Just wondering if there's any way to render the dynamic content?

The reason I'm doing this is that I am hoping to extract my markdown rendering logic out to the embedded engine: so I can deal with sanitization and whatnot in one single place

**Comment by Rakoth** [comment]
Hi @edisonywh! All embedded engines works at compile time, and not present at execution time in result template, unless you specifically does make an engine which will insert some kind-of helper call into template. 
You could accomplish what you need with
`= MyMarkdown.render(@my_markdown_from_controller)` (assuming you have such helper for markdown)

**Comment by edisonywh** [comment]
Cool I see, thanks so much for the clarification! @Rakoth
