### ISSUE TITLE
Layout inheritance

### ISSUE THREAD

**Issue by augnustin** [slime-lang/slime#154]
Hey! Great templating language here! Feels very familiar from the Rails world. :-D

I was wondering if there are any layout inheritance feature implemented:

Eg.

`base.html.slim`:

```
doctype html
html{lang="en"}
  head
    title My App
  body
      = render @view_module, @view_template, assigns
```

`app.html.slim`:

```
= render layout: 'head' do
  = render ComponentView, "navbar.html", conn: @conn
  = render @view_module, @view_template, assigns
  = render ComponentView, "footer.html", conn: @conn
```

Cheers

**Comment by augnustin** [comment]
up ?

**Comment by doomspork** [comment]
@augnustin no need to bump issues, we get to issues when we've got availability 😁 

You should be able to call `render/3` in Slime, have you tried it?

**Comment by tensiondriven** [comment]
I do this all the time in my templates - My sense is that this issue can be closed.

**Comment by doomspork** [comment]
Thank you @tensiondriven!
