### ISSUE TITLE
What is the performance compared to Eex?

### ISSUE THREAD

**Issue by rjurado01** [slime-lang/slime#159]
There is any benchmark about this template engine comparing it with EEx?

I love this template language but I would like to know about performance.

**Comment by lobo-tuerto** [comment]
If there aren't I think you could easily create them calling the render functions of both of them with different inputs.

And maybe write a blog post about it? :)

**Comment by doomspork** [comment]
@rjurado01 what concerns for performance do you have? This is compiled along with your Elixir code, just like EEx, so its performance should be identical in the final product; unlike slim itself, there is no runtime interpretation taking place on the server for Slime( or EEx).

As @lobo-tuerto mentioned, if you wanted to compare the compilation performance then you could benchmark the two render functions.

Does that help?

**Comment by rjurado01** [comment]
@doomspork Yes, It has been helpful. Thanks.
