### ISSUE TITLE
Support colon and special character for tailwind

### ISSUE THREAD

**Issue by AbdullahDahmash** [slime-lang/slime#162]
Hello

I believe this issue should have handled in different way

```slime
.relative.sm:pb-16.md:pb-20.lg:pb-28
```
Now it is converted to
```html
<div class="relative sm">
  <pb-16 class="md">
    <pb-20 class="lg">
      <pb-28>
      </pb-28>
    </pb-20>
  </pb-16>
</div>
```

But it should be converted to
```html
<div class="relative sm:pb-16 md:pb-20 lg:pb-28">
</div>
```

**Comment by AbdullahDahmash** [comment]
Similar to https://github.com/slim-template/slim/pull/841

**Comment by doomspork** [comment]
Thanks @AbdullahDahmash! @Rakoth or I will try to get to this in the not-so-distant future but if you'd like to give it a whirl PRs are welcomed :tada:

**Comment by AbdullahDahmash** [comment]
@doomspork I'm bit lost, can you give me hint where should I start?
