### ISSUE TITLE
evaluation with character sequence 'do' in a word

### ISSUE THREAD

**Issue by smeevil** [slime-lang/slime#25]
After a lot of head scratching I found the following : 

`=number_input f, :amount, class: "js-donation-amount"`

This blows up with :

```
== Compilation error on file web/views/investment_view.ex ==
** (EEx.SyntaxError) web/templates/investment/new.html.slim:1: unexpected token ' end '
    (eex) lib/eex/compiler.ex:59: EEx.Compiler.generate_buffer/4
    (phoenix) lib/phoenix/template.ex:320: Phoenix.Template.compile/2
    (phoenix) lib/phoenix/template.ex:154: Phoenix.Template."-MACRO-__before_compile__/2-fun-0-"/3
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix) expanding macro: Phoenix.Template.__before_compile__/1
    web/views/investment_view.ex:1: Sheep.InvestmentView (module)
```

This happens when I use any character sequence containing "do" in it for the class: attribute 
It seems it's not limited to the class attribute though but any for that matter.

**Comment by doomspork** [comment]
Great report @smeevil!  We will look into this

**Comment by doomspork** [comment]
Thanks so much @Rakoth, you're a machine! :+1:

**Comment by smeevil** [comment]
You guys are awesome ! :heart: 
First two weeks working with elixir / phoenix so as soon as I have a bit of a better understanding of it , I'll hope I can be of more use !

**Comment by doomspork** [comment]
Thanks @smeevil.  We'd welcome your contribution!
