### ISSUE TITLE
Add support for CLI

### ISSUE THREAD

**Issue by doomspork** [slime-lang/slime#28]
It would be great to have `slim_fast` accessible on the command line.  Additionally, it might be fun to benchmark the original Ruby implementation of `slim` against `slim_fast`.

**Comment by lpil** [comment]
What would this executable do?

**Comment by doomspork** [comment]
Truth be told @lpil I hadn't thought this through entirely.  Originally my plan was to investigate the feasibility of precompiling pages to eex to eliminate the SlimFast engine from the request stack.

This may no longer make sense in which case we can close the issue.

**Comment by lpil** [comment]
Let's close it and reopen if we have a clearer goal later :)
