### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by gusaiani** [slime-lang/slime#3]
Hi Sean,

tried to put slim_fast to work.
Created a blank Phoenix app.
Added package as dependency in `mix.exs` like all others.
Ran `mix deps.get`.

Then I tried a few things, ranging from simply changing my template’s suffix to `.slim` to adding `SlimFast.evaluate(slim, site_title: "Website Title")` to different files,  none of which worked :)

Can you give us some pointers on how to put it to work?

Once I understand it, I’ll be happy to add it to the README if that’s helpful.

Thanks

**Comment by doomspork** [comment]
Hey @gusaiani!

SlimFast's first issue, hooray :tada:

I have not yet looked at Phoenix integration but I will do that this week and get back to you.  My goal has been to get the parser as complete as possible then focus on making the package easier to use with Phoenix.

Let's leave this open and I will update it soon.

**Comment by doomspork** [comment]
I found this package for supporting HAML in Phoenix: https://github.com/chrismccord/phoenix_haml.  I'm going to read a bit more and figure out whether a separate package is necessary or not.

**Comment by doomspork** [comment]
Okay @gusaiani, I believe I've got what you want.  When you have a chance could you take a peek and see if things work for you?  The Phoenix integration is in a new package here: [phoenix_slim](https://github.com/doomspork/phoenix_slim).

Please keep in mind there may still be issues with the parser.

Thanks!

**Comment by gusaiani** [comment]
Yup, it did work in a tiny app/template and I thank you very very much for that.
It seems that live reload is not happening at the moment. 
Even though I might even trade live reload for `phoenix_slim`, I’ll test that further ;)
In fact, I'll begin porting my app and letting you know if I see crazy stuff (with fixes if I’m able).

Again: many thanks!

**Comment by doomspork** [comment]
I'll ask around this week and see if I can't make progress on live reloading.  Thanks again for your interest!

**Comment by doomspork** [comment]
@gusaiani I'm going to close this.  If you'd like to update the README with a note about Phoenix integration via `phoenix_slim`, I'd be glad to merge.

**Comment by gusaiani** [comment]
Awesome. Thanks!
