### ISSUE TITLE
No way to conditionally add attribute?

### ISSUE THREAD

**Issue by henrik** [slime-lang/slime#34]
I want to either set the "checked" attribute of a checkbox, or to have no such attribute at all. Because if the attribute is present but the value is e.g. an empty string, the box is still considered to be checked.

Not sure how to do this with slim_fast. Tried things like:

```
# Compilation error
input type="checkbox" name="meta" value="true" checked=(if @meta, do: "true")

# Not rendered correctly at all
input*[ type: "checkbox", name: "Meta", value: "true", checked: @meta ]
```

Ended up working around it by rendering the entire element in two different logic branches:

``` slim
      = if @meta do
        input type="checkbox" name="meta" value="true" checked="checked"

      = unless @meta do
        input type="checkbox" name="meta" value="true"
```

**Comment by henrik** [comment]
IIRC if you pass a nil value to an attribute in Ruby Slim, the attribute is not included.

**Comment by doomspork** [comment]
I think this is also a bug, thanks for filing @henrik.

**Comment by doomspork** [comment]
For the `nil`/`false` value attributes, these two should currently work:

``` slim
input type="checkbox" name="meta" hidden=nil value="true"
input type="checkbox" name="meta" hidden=false value="true"
```

They result in something like:

``` html
<input type="checkbox" name="meta"  value="true">
```

However, if the attribute is wrapped in `#{}` it does not work.  For instance, either of these:

``` slim
input type="checkbox" name="meta" hidden=#{nil} value="true"
input type="checkbox" name="meta" hidden=#{false} value="true"
```

Will produce:

``` html
<input type="checkbox" name="meta" hidden="" value="true">
```

@henrik could you open a second issue for the `nil`/`false` computed attribute value?

**Comment by henrik** [comment]
Hm, forgot to mention the first thing I tried: `hidden=@meta` doesn't work when `@meta` is `false` (it sets `hidden="false"` – eventhough `hidden=false` does work.

Not sure I understand what you mean about the second issue. It seems very reasonable to me that `hidden="#{false}"` would not work.

**Comment by doomspork** [comment]
I didn't quote the attribute in my example.  I would expect these to work differently:  `hidden=#{false}` vs `hidden="#{false}"`

**Comment by henrik** [comment]
Aah, you didn't. Cool, not sure if you can use an unquoted #{} like that in Ruby Slim.

**Comment by doomspork** [comment]
Good catch, you might be right @henrik.  I'll take a look.

**Comment by doomspork** [comment]
@Rakoth any thoughts on this one?  This is going to be tough since we only evaluate the EEx at the very last step.  In order to support this I believe we'll need to evaluate each and every EEx attribute and discard the `false` and `nil` values during the compile step.

**Comment by vivekcoder** [comment]
@henrik , you could do this
`input disabled==@meta`

**Comment by henrik** [comment]
@vivekcoder It didn't work before (https://github.com/slime-lang/slime/issues/34#issuecomment-138806237) but I think @Rakoth probably fixed it in that commit :) Thanks!
