### ISSUE TITLE
Over-escaped quotes in attributes

### ISSUE THREAD

**Issue by henrik** [slime-lang/slime#37]
Seems like with 0.7.1, this:

```
link rel="stylesheet" href="#{static_path(@conn, "/css/app.css")}"
```

Started producing this output:

```
<link rel="stylesheet" href=&quot;/css/app.css?vsn=625AD8D&quot;>
```

Which breaks styling because the quotes are over-escaped.

Same result if I try

```
link rel="stylesheet" href=static_path(@conn,"/css/app.css")
```

(without a space after the comma, due to #32)

**Comment by doomspork** [comment]
Thanks for the report @henrik, I'll look into it this afternoon.

**Comment by Rakoth** [comment]
Hi, @henrik could you please provide a failing test case? I cannot reproduce it.

**Comment by henrik** [comment]
Maybe there's something else about my project setup that plays into this.

You should be able to see the issue with something like

```
git clone git@github.com:henrik/qed.git
mix deps.update  # So you get 0.7.1 instead of 0.7.0
mix deps.get
mix phoenix.server
open http://localhost:4000  # And view source
```

**Comment by ivanyv** [comment]
I'm having the same issue, just created a barebones phoenix app and added the phoenixslim dependency. Just began with elixir/phoenix today so not enough knowledge to create a test case :(

**Comment by unitymind** [comment]
Confirm this issue. Exactly as described.

**Comment by doomspork** [comment]
Thanks for the reports guys.  I believe @Rakoth took a look at this any was unable to repo.  @unitymind or @ivanyv can you provide a test case that we can use?

I'll take a look at this today or tomorrow.

**Comment by henrik** [comment]
I linked my tiny Phoenix app above: maybe you can repro in there.

**Comment by doomspork** [comment]
Thanks @henrik, I can take a peek but as you said yourself "Maybe there's something else about my project setup that plays into this.".  A single failing test case lets us focus on the actual bug instead of wrestling potentially unrelated bugs or configuration issues.

I'll take a stab at putting together some test cases for this.

**Comment by henrik** [comment]
Sure. If all else fails, though, going from an error-in-app to figuring out a failing test case could be an option. It's a tiny, tiny Phoenix app.

**Comment by unitymind** [comment]
Here is initial Phoenix app: https://github.com/unitymind/boozeup
Where is take a look into `web/templates/layout/app.html.slim`

**Comment by doomspork** [comment]
0.7.2 has been released and should include a fix for this thanks to @Rakoth!

**Comment by henrik** [comment]
@doomspork @Rakoth Thanks so much! :balloon:
