### ISSUE TITLE
Support splat attributes

### ISSUE THREAD

**Issue by doomspork** [slime-lang/slime#44]
Splat converts a hash into attribute key/value pairs.

Slim:

``` slim
.card*{'data-url'=>place_path(place), 'data-id'=>place.id} = place.name
```

HTML:

``` html
<div class="card" data-id="1234" data-url="/place/1234">Slim's house</div>
```

See slim docs: [Splat Attributes](http://www.rubydoc.info/gems/slim/frames#Splat_attributes__).

**Comment by henrik** [comment]
Crucially, the hash can be returned indirectly:

```
.card *method_which_returns_hash = place.name
.card *@hash_instance_variable = place.name
```

I guess in Elixir, it could make sense to support expressions that evaluate to any type of dict, whether that's a keyword list or a map.

As for literal hash syntax, do you think it makes more sense to support the Ruby hash syntax (in your example above) for compatibility with Ruby-Slim, or to instead use some (or every) Elixir dict syntax? I'm thinking the latter.

**Comment by doomspork** [comment]
Sorry those examples were copied and pasted directly from the Slim documentation, we should definitely use Elixir dict syntax.

**Comment by henrik** [comment]
:thumbsup:

**Comment by henrik** [comment]
🎉
