### ISSUE TITLE
Textarea adds blank lines

### ISSUE THREAD

**Issue by henrik** [slime-lang/slime#48]
When I upgrade a project from slim_fast 0.7.0 to 0.9.1, the Slim code

```
textarea id="code" name="code" = "foo"
```

that previously on 0.7.0 would output

``` html
<textarea id="code" name="code">foo</textarea>
```

now on 0.9.1 outputs

``` html
<textarea id="code" name="code">foo
</textarea>
```

This leads to extra linebreaks in the received input, that were not intended.

**Comment by henrik** [comment]
Looking into this myself. Happens with `textarea = "foo"` but not `textarea foo`

**Comment by henrik** [comment]
Failing test:

``` elixir
  test "does not add linebreaks to textarea with '=' output" do
    slim = ~s"""
    textarea = "foo"
    """

    assert render(slim) == ~s(<textarea>foo</textarea>)
  end
```

Will see if I can figure out how to fix it, too, but I suspect that's trickier.

**Comment by henrik** [comment]
This change will fix my test but break a bunch of others:

``` diff
--- a/lib/slim_fast/compiler.ex
+++ b/lib/slim_fast/compiler.ex
@@ -43,7 +43,7 @@ defmodule SlimFast.Compiler do

   defp open(_, %{type: :eex, content: code, attributes: attrs}) do
     inline = if attrs[:inline], do: "=", else: ""
-    "<%#{inline} #{code} %>\n"
+    "<%#{inline} #{code} %>"
   end
```

<strike>Don't want to wrap my head around this now, so I think I'll leave it at that :)</strike>

**Comment by henrik** [comment]
I don't completely understand why those newlines are being added. They're also added e.g. inside `<title>` which seems weird. So the simplest fix would just be to not add those newlines anywhere, but I guess there's some reason they were introduced?

If the newlines should remain, I did figure out how to skip them for textareas only, though it's not super pretty: https://github.com/henrik/slim_fast/commit/2de86b34cab4e06e45dba01f3eb7d059b7248e43

**Comment by doomspork** [comment]
Hey @henrik!  I haven't had a chance to look into this yet but I suspect [this PR](https://github.com/doomspork/slim_fast/pull/35) is to blame for the newlines.
