### ISSUE TITLE
Language reference/guide

### ISSUE THREAD

**Issue by henrik** [slime-lang/slime#56]
It would be great to have a language guide somewhere, something like http://jade-lang.com/reference/ or http://www.rubydoc.info/gems/slim/frames. It could go through all the syntax we support, with examples. Especially seeing as we don't map exactly to Ruby Slim.

We could also mention any current limitations with stuff we have yet to implement, gotchas and such.

https://github.com/elixir-lang/ex_doc supports "extras" so maybe that would make sense. Or could we get a usable guide out of the moduledocs (#18) without writing "extras"?

**Comment by henrik** [comment]
Also see Calliope for inspiration: https://github.com/nurugger07/calliope#embedded-elixir

**Comment by lpil** [comment]
:+1:

**Comment by lpil** [comment]
I'm gunna start working on this.
