### ISSUE TITLE
Automatically self-close some tags

### ISSUE THREAD

**Issue by henrik** [slime-lang/slime#57]
With #50 we can explicitly ask for a self-closing tag.

Ruby Slim also _automatically_ closes the usual suspects – [see docs](http://www.rubydoc.info/gems/slim/frames#Closed_tags__trailing___):

> Note, that this is usually not necessary since the standard html tags (img, br, ...) are closed automatically.

We don't seem to do that currently, but it might be fairly easy to add on top of @vicmargar's work in #50.

List of self-closing tags: http://stackoverflow.com/questions/13915201/what-tags-in-html5-are-acknowledged-of-being-self-closing

**Comment by doomspork** [comment]
Sounds good to me.  Seems like a pretty straightforward addition.
