### ISSUE TITLE
Benchmarks against eex, calliope, etc.

### ISSUE THREAD

**Issue by lpil** [slime-lang/slime#58]
It'd be great if we can see how this library performs.

**Comment by doomspork** [comment]
This is a great idea.  Is this something you're interested in tackling @lpil?  @henrik I know you started on some benchmarking, would you be interested in helping with this?

**Comment by lpil** [comment]
The problem I'm having is that I don't really know how to go about comparing like with like. Do we render HTML pages that are equivalent, even though the output would differ due to this library effectively doing HTML minification, while EEx would not?

**Comment by doomspork** [comment]
I don't believe this adds much value, so I'm closing this.  If someone wants to do this as a blog post go for it 👍
