### ISSUE TITLE
id attributes are not merged

### ISSUE THREAD

**Issue by lpil** [slime-lang/slime#66]
``` elixir
  test "shorthand and literal id attributes are merged" do
    template = ~s(#id-one id="id-two")
    assert render(template) == ~s(<div id="id-one id-two"></div>)
  end
```

This fails.

**Comment by doomspork** [comment]
I don't believe this is intended behavior or should be added.  The resulting HTML appears to be invalid:

HTML4: http://www.w3.org/TR/html4/types.html#type-id
HTML5: http://www.w3.org/TR/html5/dom.html#the-id-attribute

**Comment by lpil** [comment]
Huh. I'd no idea.

**Comment by doomspork** [comment]
I just learned it myself! :grinning:
