### ISSUE TITLE
Refactor Slime.Parser

### ISSUE THREAD

**Issue by lpil** [slime-lang/slime#67]
I'm finding this module very difficult to read and to modify, and I think it would be a good candidate for refactoring.

Use of module attributes over string literals makes it difficult to understand which function definition is going to match without scrolling to the top of the module to read their assignments.

Lots of the functions are complex and difficult to understand the intent of.

**Comment by doomspork** [comment]
I'm almost always onboard with refactors so this sound good to me.  The goal was to ship something and then make it better.  Now is the making better part :grinning:

**Comment by dannote** [comment]
I completely agree. It seems that the whole parser needs to be rewritten using tokenizer rather than regexp magic. That will also allow to provide adequate parse error messages. Even more, the compiler needs to be rewritten too, without using EEx templates as the middle representation.

**Comment by dannote** [comment]
Maybe using `leex` would be better solution for this case.

**Comment by lpil** [comment]
I've actually started working on a reimplementation, though I've not worked on it for a while due to life stuff. It's written in an extendable manner, so once ask the basic features are in I would suggest it replace slime entirely.

https://github.com/lpil/jot

**Comment by doomspork** [comment]
Howdy @lpil, I was wondering why you had abandoned your efforts and left the org.  Now I see it was to roll the project as your own for those almighty GitHub stars, disappointing but not surprising.

Best of luck.  Closing this issue for the time.

**Comment by lpil** [comment]
Not for stars, but to see if we could implement a Slime like templating language in Elixir in a fashion that is easy to maintain and doesn't depend on EEx :)
