### ISSUE TITLE
Use a struct to represent a parsed line in Slime.Parser

### ISSUE THREAD

**Issue by lpil** [slime-lang/slime#69]
A large unlabelled tuple is much less clear and harder to modify than a struct.

**Comment by doomspork** [comment]
:+1:

**Comment by lpil** [comment]
Actually a record might make more sense here.

**Comment by doomspork** [comment]
A record is basically a tuple, how does that help us here?

**Comment by lpil** [comment]
With a record the fields are named, which makes it much more readable, and enforces a schema on our data.

**Comment by lpil** [comment]
It's only really benefit over a struct is speed. This probably doesn't matter. We can use a struct. :)

**Comment by doomspork** [comment]
Thanks for clearing that up :grinning:
