### ISSUE TITLE
Support multi-line verbatim text

### ISSUE THREAD

**Issue by doomspork** [slime-lang/slime#7]
SlimFast supports verbatim and verbatim w/ whitespace but only on one line.  Per the slim documentation, any subsequent lines with a deeper indentation are included.

**Comment by gusaiani** [comment]
+1

Just tried to write a `<pre>` tag:

``` slim
pre
  | defmodule R do
      def reload! do
        Mix.Task.reenable "compile.elixir"
          Application.stop(Mix.Project.config[:app])
          Mix.Task.run "compile.elixir"
          Application.start(Mix.Project.config[:app], :permanent)
      end
    end
```

and it didn’t get formatted as it does in Rails.
Looks like what you’re describing in the issue I suppose.

**Comment by Rakoth** [comment]
I am working on this.

**Comment by doomspork** [comment]
That's great @Rakoth, thank you! :+1:

**Comment by gusaiani** [comment]
:+1: @Rakoth
