### ISSUE TITLE
Use the yecc parser generator instead of lots of regexes

### ISSUE THREAD

**Issue by lpil** [slime-lang/slime#73]
Pygments has a BNF we might be able to use.

https://bitbucket.org/birkenfeld/pygments-main/src/cb583a0e37c776b77e3c49200c1658c920e9845a/pygments/lexers/webmisc.py?at=default&fileviewer=file-view-default#webmisc.py-885

This isn't something I know anything about, so should be fun!

https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_Form

**Comment by doomspork** [comment]
Sounds new and exciting to me.  I'm down to learn more about Yecc

**Comment by Rakoth** [comment]
I was trying to use leex and yecc to replace current parser (actually lexer) and compiler + tree (parser), but without success. Main problem with leex lexer: there is no way to match beginning of line. I have no experience with this, though. Also this guys was trying to do the same https://github.com/sydneyelixir/slex .
I came across this project: https://github.com/seancribbs/neotoma it looks like we can use it.

**Comment by lpil** [comment]
> there is no way to match beginning of line

I'm confused, I thought it was pretty much just a mapping of RE regex to tokens? Is that not the case?

Can we anchor onto the previous line's newline rather than start of line?

I'd like to avoid stepping out of the standard library. If we can't use leex and yecc we can just clean up our hand rolled parser.

**Comment by lpil** [comment]
Spent some time playing tonight. It's easy to match on the previous newline, but I know so little of this stuff everything else is very slow progress.

**Comment by dgmcguire** [comment]
I'm playing with this and curious if you're still wanting to replace the regex's and current implementations to use leex/yecc?  If so I'll give it a go, if not I'll just tinker around for fun.

**Comment by doomspork** [comment]
Howdy @dgmcguire!  Have you seen PR #84?  @lpil took an initial stab at this.  Probably worth syncing up with him to see whether it's something he's going to continue or whether you can take over.

Thanks your interest :grinning:

**Comment by lpil** [comment]
To say I took a stab is very generous. I literally just made a file, and then lost interest ;)

Certainly happy to accept contributions here!

**Comment by dgmcguire** [comment]
Cool, I'm new to elixir, just got done getting a dumb application cobbled together using leex/yecc, so I'll have a go at implementing them in this project.  Don't expect much and I won't disappoint :) - my end goal will be to implement a feature for supporting a user defined config file that allows making their own tags/attr [shortcuts](http://www.rubydoc.info/gems/slim/frames#Shortcuts), but I'll start with leex/yecc as that might shed some light on a good way to go about achieving that goal.

**Comment by lpil** [comment]
The ability to define would come after the parsing stage, so it doesn't matter if we use leex or yecc for anything here :)

**Comment by dgmcguire** [comment]
I'm not sure that's right unless you have a completely different implementation in mind than I do.  For instance, I have a wrapper around slim in ruby that expands `.klass@@users` to `<div class="klass" data-scope="users"></div>` - I'm not immediately understanding how someone could do that without new lexer/parser rules.

Am I misunderstanding something?  I'm pretty new to all these concepts, really.

**Comment by lpil** [comment]
Ah, I see. I was only looking at the example that expanded `c` to `container`.

**Comment by lpil** [comment]
I don't feel that yecc and leex are overly suited to the task now.
