### ISSUE TITLE
Come up with a catchy tag line / description

### ISSUE THREAD

**Issue by lpil** [slime-lang/slime#77]
Slim:

> A lightweight templating engine.
> Slim is a template language whose goal is reduce the syntax to the essential parts without becoming cryptic.

Jade:

> Jade - robust, elegant, feature rich template engine for Node.js

HAML:

> Beautiful, DRY, well-indented, clear markup: templating haiku.

**Comment by doomspork** [comment]
In addition to a catch phrase I'd like to come up with a single logo.

**Comment by lpil** [comment]
That'd be great!

**Comment by henrik** [comment]
Are we aiming for catchy or informative? Not sure any of those examples are catchy as such :)

If we want to go for informative, maybe something like: "Minimalistic HTML templates for Elixir, inspired by Slim." Or "A minimalistic templating engine …" if we want to focus on that.

**Comment by doomspork** [comment]
Just spitballing: 

> Tasty templates
> 
> Slimed down templates in Elixir
> 
> The no-fluff stuff
> 
> Less markup, more remarkable

**Comment by henrik** [comment]
> Ooze drippin' good

;) (Not a good idea.)

**Comment by lpil** [comment]
>  "Minimalistic HTML templates for Elixir, inspired by Slim."

Works for me.

**Comment by doomspork** [comment]
Updated the project description: "Minimalistic HTML templates for Elixir, inspired by Slim."
