### ISSUE TITLE
Any plans to support embedded engines?

### ISSUE THREAD

**Issue by micahwedemeyer** [slime-lang/slime#87]
As in, the ability to embed markdown, javascript, coffeescript, etc, etc?

http://www.rubydoc.info/gems/slim/frames#Embedded_engines__Markdown______

I can understand if that's a far-futures goal, but if so, it might be a good idea to update the README to explicitly state that it's not supported.

**Comment by lpil** [comment]
At some point, but there's a lot to do first. I'd certainly like to support markdown.

> it might be a good idea to update the README to explicitly state that it's not supported.

Documenting features we don't have sounds like it would cause confusion.

**Comment by micahwedemeyer** [comment]
Ah, I'm sorry. I didn't realize you had set up slime-lang.com. I was still going off of slim-lang.com, and that's where my confusion came from. I get it now.

**Comment by lpil** [comment]
It's all in-progress at the moment. Hopefully we'll have better documentation soon.

**Comment by Awea** [comment]
inline javascript support is planned ? Like:

``` slim
javascript:
  console.log('foo')
```

**Comment by lpil** [comment]
I think so, though there is no clear timeframe. I'm more interested in doing a major refactoring of the parser than anything else.

**Comment by Awea** [comment]
@lpil sounds legit ^^
