### ISSUE TITLE
Blank lines in the template generate empty divs

### ISSUE THREAD

**Issue by campezzi** [slime-lang/slime#92]
When writing a template, leaving a blank line between two elements generates an empty `<div>` in the resulting HTML code. This only seems to happen if the blank line contains a certain number of whitespace characters, a common scenario when using editors that auto-indent. This doesn't seem to be the desired behavior (it does not happen in the Ruby implementation of Slim).

Example:

```
  p First Paragraph

  p Second Paragraph
```

(note: GitHub is stripping white spaces, but that blank line between the two `p` elements includes 2 white spaces, preserving indentation of said elements)

Generates:

```
<p>First Paragraph</p>
<div></div>
<p>Second Paragraph</p>
```

**Comment by lpil** [comment]
Thanks for the report :)

**Comment by campezzi** [comment]
No problem. I'll try to take a look at the code later and see if I can contribute a fix!

**Comment by doomspork** [comment]
@campezzi the fix for this will be released later this weekend :+1:

**Comment by doomspork** [comment]
@campezzi `0.12.2` has been released with this fix.

**Comment by campezzi** [comment]
Thanks, I'll give it a go!
