### ISSUE TITLE
Support javascript

### ISSUE THREAD

**Issue by maxgronlund** [slime-lang/slime#97]
Thanks for a great parser

I would love to be able to do stuff like this

```
javascript:
      alert('Slim supports embedded javascript!')
```

**Comment by lpil** [comment]
A good idea :)

**Comment by lessless** [comment]
Just bumped into that one - a total must have for sure! Is it in the queue?

**Comment by lpil** [comment]
I'm not sure that anyone is working on features for Slime at the moment I'm afraid.

**Comment by lessless** [comment]
There is a simple workaround towards this issue - wrap JS part in the `EEX` template, so this is rather _very, very good to have_, but not critical.

**Comment by taakazazzz** [comment]
@lessless what do you mean exactly?

**Comment by Rakoth** [comment]
I am working on it

**Comment by Rakoth** [comment]
Guys, please checkout #101
