### ISSUE TITLE
Attribute list delimiter option

### ISSUE THREAD

**Issue by ghost** [slime-lang/slime#98]
Hi!

Is it possible to add something similar to slim's [Attribute list delimiter option `:attr_list_delims`](https://github.com/slim-template/slim#available-options)? It would resolve a conflict between the interpolation markers `{{ }}` some js libraries use and slime's own attribute list delimiters `{ }`.

**Comment by lpil** [comment]
A good suggestion! Currently I'm interested in working on improving code quality more than introducing new features. Perhaps someone else will be interested.
