### ISSUE TITLE
Applications list in mix.exs

### ISSUE THREAD

**Issue by Awea** [slime-lang/slime#99]
I'm using Slime in a small project of mine and I recently have to deal with the release process using [exrm](https://github.com/bitwalker/exrm). For slime I have to add this to my applications list : 

``` elixir
def application do
[applications: [:eex]]
end
```

This shouldn't be added to this project by default ?

**Comment by lpil** [comment]
Yes, I think so. PRs welcome :)

**Comment by Awea** [comment]
@lpil done ^^
